name: CedarConsultants
favicon: null
layout_spectrum: 0.3998490732628852
typography_spectrum: 0.5400318156462163
title: Sales and Marketing Consultants
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9664551836904138
  lightness: 0.01691375905647874
  saturation: 0.2063030896242708
  rhythmicContrast: 0.7032016238663346
purpose: []
